export const localidadesMexico = [
    "Aguascalientes",
    "Asientos",
    "Calvillo",
    "Jesús María",
    "San Francisco de los Romo",
    "Ensenada",
    "Mexicali",
    "Tijuana",
    "La Paz",
    "Cabo San Lucas",
    "Campeche",
    "Carmen",
    "Calkiní",
    "Saltillo",
    "Torreón",
    "Monclova",
    "Colima",
    "Manzanillo",
    "Villa de Álvarez",
    "Tuxtla Gutiérrez",
    "San Cristóbal de las Casas",
    "Ciudad Juárez",
    "Chihuahua",
    "Delicias",
    "Gómez Palacio",
    "Durango",
    "Irapuato",
    "León",
    "Celaya",
    "Acapulco",
    "Chilpancingo",
    "Pachuca",
    "Tulancingo",
    "Guadalajara",
    "Zapopan",
    "Puerto Vallarta",
    "Ecatepec",
    "Toluca",
    "Morelia",
    "Zamora",
    "Cuernavaca",
    "Yautepec",
    "Tepic",
    "Monterrey",
    "San Nicolás de los Garza",
    "Oaxaca",
    "Salina Cruz",
    "Puebla",
    "Tehuacán",
    "Querétaro",
    "San Luis Potosí",
    "Mazatlán",
    "Culiacán",
    "Hermosillo",
    "Nogales",
    "Villahermosa",
    "Ciudad Victoria",
    "Tampico",
    "Xalapa",
    "Veracruz",
    "Cancún",
    "Mérida",
    "Zacatecas",
    "Fresnillo",
  ];